### ISSUE TITLE
Add ability to read N_SIGMA column in wcptab

### ISSUE THREAD

**Issue by stscirij** [spacetelescope/calcos#13]
Currently the value of N_SIGMA, the chi-squared threshold used in the wavelength calibration, is hard coded at 15.0.  This will probably not work at LP4 where some of the wavecal spectra will be gain-sagged, so will be missing lines.  For lp4 and later, wcptab ref files will have a new column, N_SIGMA, which has the threshold to be used instead of the default.  Calcos should check for this column and use the contents if it is there, reverting to the default if not.  PR 86840 describes this:
https://www.ess.stsci.edu/prsystem/servlet/prbrowse/pr.86840

**Comment by Rplesha** [comment]
Fixed in 5962b7780eb2771dac22e920f52b0a6f46f18471. Issue can be closed.
