### ISSUE TITLE
3.3.10 to astroconda, please

### ISSUE THREAD

**Issue by parkus** [spacetelescope/calcos#174]
Using pip to update to 3.3.10 works for now, but it took me a while to figure out that my astroconda distribution of calcos was stuck at 3.3.9 and realize I could use pip to get the latest version. The astroconda channel is very nice for those like me who don't really understand packages :)

**Comment by stscirij** [comment]
Thanks for the tipoff - we usually upgrade automatically after a pipeline release but for some reason this didn't happen.  I'll look into getting this done.

**Comment by nden** [comment]
Calcos 3.3.10 is now in astroconda.
