### ISSUE TITLE
Fix fuv_timetag_1.test_fuv_timetag_1 test on pandokia

### ISSUE THREAD

**Issue by pllim** [spacetelescope/calcos#18]
Example log: https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&key_id=125033830

*Type: NameError Message: POLICY WARNING: Exception message is too long: 36779 > 255 name 'a' is not defined -------------------- >> begin captured stdout << --------------------- CALCOS version 3.2.1 (2017-04-28) numpy version 1.12.1 astropy version 3.0.dev20729 Begin 28-Nov-2017 10:41:28 EST Association file = lckg01070_asn.fits TIME-TAG calibration -- 28-Nov-2017 10:41:31 EST Input lckg01czq_rawtag_a.fits OutTag lckg01czq_corrtag_a.fits OutFlt lckg01czq_flt_a.fits OutCounts lckg01czq_counts_a.fits OutFlash lckg01czq_lampflash_a.fits DETECTOR FUV, segment A EXPTYPE EXTERNAL/SCI OPT_ELEM G140L, CENWAVE 1280, FPOFFSET -2 APERTURE PSA BADTCORR OMIT RANDCORR PERFORM RANDSEED = 100 TEMPCORR PERFORM BRFTAB = lref$x1u1459il_brf.fits GEOCORR PERFORM GEOFILE = lref$x1u1459gl_geo.fits IGEOCORR PERFORM DGEOCORR OMIT XWLKCORR PERFORM XWLKFILE= lref$14o2013ql_xwalk.fits YWLKCORR PERFORM YWLKFILE= lref$14o2013rl_ywalk.fits DEADCORR PERFORM DEADTAB = lref$s7g1700gl_dead.fits Last time int...*

**Comment by philhodge** [comment]
It looks as if there's a problem with the test script (note the last 
line, "name 'a' is not defined"):

   File "/srv/rt/stsci_python/calcos/fuv_timetag_1/fuv_timetag_1.py", line 79, in write_report
     print(a.report())

EXCEPTION
Type: NameError
Message:

POLICY WARNING: Exception message is too long: 36779 > 255

name 'a' is not defined

**Comment by pllim** [comment]
Undefined "a" is gone, so now it is failing with `fitsdiff` differences. FYI -- https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&key_id=125201911

**Comment by pllim** [comment]
Update: I spoke with @stscirij and the conclusion is to understand why this difference below occurs in dev but not public. In addition, we also resolved the mystery of the test missing on the other machine (had to manually invoke `svn update`).

```
 fitsdiff: 3.0.dev20763
 a: lckg01czq_corrtag_a.fits
 b: .../cos/regtest_data/fuv_timetag_1/lckg01czq_corrtag_a.fits
 Keyword(s) not to be compared:
  CAL_VER DATE
 Maximum number of different data values to be reported: 10
 Relative tolerance: 0.0, Absolute tolerance: 0.0

Extension HDU 3:

   Headers contain differences:
     Headers have different number of cards:
      a: 290
      b: 298
     Extra keyword 'TCRPX2' in b: 1.0
     Extra keyword 'TCRPX3' in b: 1.0
     Extra keyword 'TCRVL2' in b: -999.0
     Extra keyword 'TCRVL3' in b: -999.0
     Extra keyword 'TCTYP2' in b: 'RA---TAN'
     Extra keyword 'TCTYP3' in b: 'ANGLE'
     Extra keyword 'TCUNI2' in b: 'angstrom'
     Extra keyword 'TCUNI3' in b: 'deg'
```

**Comment by pllim** [comment]
A different error now: https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&key_id=131644158

```
CALCOS version 3.2.1 (2017-04-28)
numpy version 1.13.1
astropy version 3.1.dev21140
Begin 07-Jan-2018 10:41:33 EST
Association file = lckg01070_asn.fits
ERROR:  output file already exists:
ERROR:    lckg01czq_lampflash_a.fits
  File "/srv/iraf/bldtmp/pdR9/p/envs/dev/lib/python3.5/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/srv/iraf/bldtmp/pdR9/p/envs/dev/lib/python3.5/unittest/case.py", line 605, in run
    testMethod()
  File "/srv/iraf/bldtmp/pdR9/p/envs/dev/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/srv/rt/stsci_python/calcos/fuv_timetag_1/fuv_timetag_1.py", line 39, in test_fuv_timetag_1
    status = calcos.calcos(infile)
  File "/srv/iraf/bldtmp/pdR9/p/envs/dev/lib/python3.5/site-packages/calcos/calcos.py", line 424, in calcos
    assoc = Association(asntable, outdir, cl_args)
  File "/srv/iraf/bldtmp/pdR9/p/envs/dev/lib/python3.5/site-packages/calcos/calcos.py", line 797, in __init__
    self.checkOutputExists()
  File "/srv/iraf/bldtmp/pdR9/p/envs/dev/lib/python3.5/site-packages/calcos/calcos.py", line 1753, in checkOutputExists
    raise RuntimeError(errmess)

EXCEPTION
Type: RuntimeError
Message: output file already exists
-------------------- >> begin captured stdout << ---------------------
CALCOS version 3.2.1 (2017-04-28)
numpy version 1.13.1
astropy version 3.1.dev21140
Begin 07-Jan-2018 10:41:33 EST
Association file = lckg01070_asn.fits
ERROR:  output file already exists:
ERROR:    lckg01czq_lampflash_a.fits

--------------------- >> end captured stdout << ----------------------
Trigger: raise RuntimeError(errmess)
```

**Comment by pllim** [comment]
Now it is this:
```
Extension HDU 1:

   Headers contain differences:
     Keyword CRPIX1   has different comments:
        b> axis1 pixel of tangent plane direction
     Keyword CRPIX2   has different comments:
        b> axis2 pixel of tangent plane direction
     Keyword CRVAL1   has different comments:
        b> sky coordinates of 1st axis
     Keyword CRVAL2   has different comments:
        b> sky coordinates of 2nd axis
     Keyword CTYPE1   has different comments:
        b> axis type for dimension 1
     Keyword CTYPE2   has different comments:
        b> axis type for dimension 2
     Keyword CUNIT1   has different comments:
        b> units of first coordinate value
```
