### ISSUE TITLE
best way to cite

### ISSUE THREAD

**Issue by afeinstein20** [spacetelescope/calcos#199]
Hi! What is the best way to cite this and the `costools` repositories? I plan on including links to the GitHub and have also cited the COS Data Handbook (since `calcos` is mentioned in there). Thanks!

**Comment by stscirij** [comment]
This is probably the best way to go - there are some very early documents that were written very early in the developement of the project, but they are now very much out of date and referencing the GitHub repos and the Data Handbook will be the most useful paper trail for those wanting more info.  Thanks!
