### ISSUE TITLE
Fix bug in extraction routine where calcos would crash if background region outside data array of PROFTAB array

### ISSUE THREAD

**Issue by stscirij** [spacetelescope/calcos#20]
From PR# 89521: CalCOS Profile Background Subtraction Bug

Calcos should be able to handle the situation where one of the background
regions is outside the profile image. In fact, every time the background is
calculated there are conditional statements to cover the situation. However,
there is a minor coding oversight in the extraction routine that causes an
inevitable crash when either of the background regions extends outside the
profile image.

1) Make sure any variables using BKG_1 or BKG2 are contained in the case where
one doesn't exist in "extract.py".

2) Fix typo in "trace.py":
cosutil.printMsg("Unable to extract background region #2 from", \
                 " reference profile")

**Comment by Rplesha** [comment]
Fixed in af840516d2b55b541ffc4d9c67228510fa832977. Issue can be closed.
