### ISSUE TITLE
Change github actions to run on all pytests

### ISSUE THREAD

**Issue by Rplesha** [spacetelescope/calcos#211]
Fix the line: https://github.com/spacetelescope/calcos/blob/master/.github/workflows/python_testing.yml#L67 so that all tests are run, not just cosutil

**Comment by stscirij** [comment]
We're trying to get the bug fix in by tomorrow morning, so maybe best to wait.  Also, I'd like to have the unit tests clean up after themselves better - currently they leave a lot of temporary files in the current directory so if you run the tests with pytest they make a mess of the tests directory.

**Comment by stscirij** [comment]
Fixed in #218

**Comment by stscirij** [comment]
Fixed in #218
