### ISSUE TITLE
Missing parameters when calling timetag.doDqicorr in x1d.py

### ISSUE THREAD

**Issue by ladsantos** [spacetelescope/calcos#23]
In line 447 of x1d.py, the call to the function `timetag.doDqicorr` is missing two required positional arguments: `traceprofile` and `gti`.

**Comment by stscirij** [comment]
Duplicates #16

**Comment by stscirij** [comment]
See https://stsci.service-now.com/hst?id=kb_article&sys_id=feb1ccd9db24db80fb50f9baae9619d5
