### ISSUE TITLE
Calibrating gzipped ACCUM data exposes a bug in astropy

### ISSUE THREAD

**Issue by jotaylor** [spacetelescope/calcos#25]
This is because when ACCUM products are created, a PrimaryHDU is first created, then ImageHDUs are appended in astropy's append mode:
https://github.com/spacetelescope/calcos/blob/af840516d2b55b541ffc4d9c67228510fa832977/lib/calcos/accum.py#L794
This has been filed as an issue with astropy:
https://github.com/astropy/astropy/issues/7457
In the context of calcos this is easily fixed by using update mode rather than append mode.

**Comment by stscirij** [comment]
Fixed in #26
