### ISSUE TITLE
TST: Mark TestFUVTimetag as slow when more tests are available

### ISSUE THREAD

**Issue by pllim** [spacetelescope/calcos#39]
Follow up of #30 and related to #12. When more tests are added, the one added in #30 should be marked as slow by uncommenting `@pytest.mark.slow` and delete the `TODO` comment (see below). Currently, it is the only test, so it needs to run regardless.

```python
# TODO: Mark this as slow when there are faster tests added for CI tests
#       so that this only runs in nightly tests.
#@pytest.mark.slow
class TestFUVTimetag(BaseCOS):
    ...
```

**Comment by stscirij** [comment]
This has been fixed
