### ISSUE TITLE
TST: Enable nightly test (again)

### ISSUE THREAD

**Issue by pllim** [spacetelescope/calcos#41]
https://boyle.stsci.edu:8081/job/RT/job/calcos/test_results_analyzer/ is broken by #40 as it currently does not support multiple builds like the push event one. Matt will investigate ways to make this possible for `JenkinsfileRT` as it is with `Jenkinsfile`.

**Comment by rendinam** [comment]
Corrected by spacetelescope/jenkins_shared_ci_utils#17 and #43.
