### ISSUE TITLE
CalCOS crashes if there aren't enough counts in TWOZONE extraction

### ISSUE THREAD

**Issue by Rplesha** [spacetelescope/calcos#44]
During the centroid calculation, if CalCOS does not find counts in the extraction region it crashes with a TypeError:
`~/anaconda/envs/astroconda_3/lib/python3.6/site-packages/calcos/trace.py in calculateCentroidError(data_ij, goodcolumns, regions, centroid, background)
    489     y = rows[:,np.newaxis]
    490     sumi = (i - background).sum(axis=0, dtype=np.float64)[goodcolumns].sum(dtype=np.float64)
--> 491     sumsq = (i*(y - centroid) * \
    492                  (y - centroid)).sum(axis=0,
    493                                      dtype=np.float64)[goodcolumns].sum(dtype=np.float64)
 
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'`

Instead, CalCOS should check to make sure there are counts in the exposure to extract in the first place, and if there are none to use the default locations in the XTRACTAB/TWOZXTAB reference files and not calculate a centroid. It should also print a warning that it is doing this.

**Comment by stscirij** [comment]
@rplesha can you point me to a dataset that invokes this exception?

**Comment by Rplesha** [comment]
@stscirij ldmw3cg6q with RANDSEED=1537735096 is an example of this happening. I think it is in the association ldmw3c010.
