### ISSUE TITLE
numpy deprecation warnings runing calcos under pytest

### ISSUE THREAD

**Issue by stscirij** [spacetelescope/calcos#49]
Many warnings that look like this:

/opt/conda/envs/tmp_env1/lib/python3.6/site-packages/calcos-3.3.4-py3.6-linux-x86_64.egg/calcos/wavecal.py:827: DeprecationWarning: NPY_ARRAY_UPDATEIFCOPY, NPY_ARRAY_INOUT_ARRAY, and NPY_ARRAY_INOUT_FARRAY are deprecated, use NPY_WRITEBACKIFCOPY, NPY_ARRAY_INOUT_ARRAY2, or NPY_ARRAY_INOUT_FARRAY2 respectively instead, and call PyArray_ResolveWritebackIfCopy before the array is deallocated, i.e. before the last call to Py_DECREF.

**Comment by Rplesha** [comment]
This hasn't been delivered yet. My bot closed it prematurely.
